Description: >
  Lambda function with container

Parameters:
  FunctionName:
    Type: String

  ImageUri:
    Type: String

Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Role:
        Fn::GetAtt:
          - "FunctionRole"
          - "Arn"
      Timeout: 25
      Code:
        ImageUri: !Ref ImageUri
      PackageType: Image

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
