Description: >
  Lambda function classic

Parameters:
  S3Bucket:
    Type: String

  S3Key:
    Type: String

  FunctionName:
    Type: String

Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: "main.run"
      Role:
        Fn::GetAtt:
          - "FunctionRole"
          - "Arn"
      Runtime: "python3.8"
      Timeout: 25
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
